### ISSUE TITLE
Add support China region

### ISSUE THREAD

**Issue by liangruibupt** [aws-samples/serverless-refarch-for-proxysql#4]
cdk --app lib/index.js deploy ProxySQL --region cn-northwest-1

```bash
(node:27141) ExperimentalWarning: The fs.promises API is experimental
/home/ec2-user/workspace/serverless-refarch-for-proxysql/node_modules/@aws-cdk/aws-lambda/lib/function.js:71
            throw new Error(`Environment variables are not supported in this region (${region}); consider using tags or SSM parameters instead`);
            ^

Error: Environment variables are not supported in this region (cn-northwest-1); consider using tags or SSM parameters instead
    at new Function (/home/ec2-user/workspace/serverless-refarch-for-proxysql/node_modules/@aws-cdk/aws-lambda/lib/function.js:71:19)
    at new ProxysqlFargate (/home/ec2-user/workspace/serverless-refarch-for-proxysql/lib/index.js:87:25)
    at Object.<anonymous> (/home/ec2-user/workspace/serverless-refarch-for-proxysql/lib/index.js:110:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
Subprocess exited with error 1
```

**Comment by pahud** [comment]
Thanks for the feedback. I'll refresh this repo and make sure it works in China.
